export const MIDI_CC_MAP = {
  1: { name: "Mod Wheel", target: "lfo1Depth" },
  2: { name: "Breath Controller", target: "filterQ" },
  7: { name: "Channel Volume", target: "masterVolume" },
  10: { name: "Pan", target: "reserved" },
  11: { name: "Expression", target: "expression" },
  20: { name: "Undefined 20", target: "osc1Level" },
  21: { name: "Undefined 21", target: "osc2Level" },
  22: { name: "Undefined 22", target: "osc1Detune" },
  23: { name: "Undefined 23", target: "osc2Detune" },
  24: { name: "Undefined 24", target: "osc1Octave" },
  25: { name: "Undefined 25", target: "osc2Octave" },
  26: { name: "Undefined 26", target: "fxDelayTime" },
  27: { name: "Undefined 27", target: "fxDelayFeedback" },
  28: { name: "Undefined 28", target: "fxDelayMix" },
  29: { name: "Undefined 29", target: "fxChorusRate" },
  30: { name: "Undefined 30", target: "fxChorusDepth" },
  31: { name: "Undefined 31", target: "fxChorusMix" },
  64: { name: "Sustain Pedal", target: "sustainPedal" },
  71: { name: "Resonance", target: "filterQ" },
  72: { name: "Release Time", target: "release" },
  73: { name: "Attack Time", target: "attack" },
  74: { name: "Brightness", target: "filterCutoff" },
  75: { name: "Decay Time", target: "decay" },
  76: { name: "Vibrato Rate", target: "lfo1Rate" },
  77: { name: "Vibrato Depth", target: "lfo1Depth" },
  78: { name: "Vibrato Delay", target: "reserved" },
  85: { name: "Undefined 85", target: "fxReverbSize" },
  86: { name: "Undefined 86", target: "fxReverbMix" },
  87: { name: "Undefined 87", target: "fxDistDrive" },
  88: { name: "Undefined 88", target: "fxDistMix" },
  120: { name: "All Sound Off", target: "allSoundOff" },
  123: { name: "All Notes Off", target: "allNotesOff" },
};

export const LFO_DIVISION_BEATS = {
  "1/1": 4,
  "1/2": 2,
  "1/4": 1,
  "1/8": 0.5,
  "1/16": 0.25,
  "1/32": 0.125,
  "1/4T": 2 / 3,
  "1/8T": 1 / 3,
  "1/16T": 1 / 6,
  "1/4.": 1.5,
  "1/8.": 0.75,
  "1/16.": 0.375,
};

export const PARAM_CONFIG = {
  osc1Octave: { min: -2, max: 2, step: 1, digits: 0 },
  osc2Octave: { min: -2, max: 2, step: 1, digits: 0 },
  osc1Detune: { min: -50, max: 50, step: 1, digits: 0 },
  osc2Detune: { min: -50, max: 50, step: 1, digits: 0 },
  osc1Level: { min: 0, max: 1, step: 0.01, digits: 2 },
  osc2Level: { min: 0, max: 1, step: 0.01, digits: 2 },
  filterCutoff: { min: 0, max: 127, step: 1, digits: 0 },
  filterQ: { min: 0, max: 127, step: 1, digits: 0 },
  attack: { min: 0, max: 127, step: 1, digits: 0 },
  decay: { min: 0, max: 127, step: 1, digits: 0 },
  sustain: { min: 0, max: 127, step: 1, digits: 0 },
  release: { min: 0, max: 127, step: 1, digits: 0 },
  lfo1Rate: { min: 0.01, max: 20, step: 0.01, digits: 2 },
  lfo1Depth: { min: 0, max: 1, step: 0.01, digits: 2 },
  lfo2Rate: { min: 0.01, max: 20, step: 0.01, digits: 2 },
  lfo2Depth: { min: 0, max: 1, step: 0.01, digits: 2 },
  fxDelayTime: { min: 0, max: 127, step: 1, digits: 0 },
  fxDelayFeedback: { min: 0, max: 127, step: 1, digits: 0 },
  fxDelayMix: { min: 0, max: 127, step: 1, digits: 0 },
  fxChorusRate: { min: 0, max: 127, step: 1, digits: 0 },
  fxChorusDepth: { min: 0, max: 127, step: 1, digits: 0 },
  fxChorusMix: { min: 0, max: 127, step: 1, digits: 0 },
  fxReverbSize: { min: 0, max: 127, step: 1, digits: 0 },
  fxReverbMix: { min: 0, max: 127, step: 1, digits: 0 },
  fxDistDrive: { min: 0, max: 127, step: 1, digits: 0 },
  fxDistMix: { min: 0, max: 127, step: 1, digits: 0 },
  masterVolume: { min: 0, max: 1, step: 0.01, digits: 2 },
};

export const DEFAULT_PARAMS = {
  osc1Wave: "triangle",
  osc1Octave: 0,
  osc1Detune: 0,
  osc1Level: 0.5,
  osc2Wave: "sawtooth",
  osc2Octave: 0,
  osc2Detune: 0,
  osc2Level: 0.5,
  filterCutoff: 109,
  filterQ: 4,
  attack: 1,
  decay: 13,
  sustain: 89,
  release: 12,
  lfo1Wave: "sine",
  lfo1Target: "off",
  lfo1Rate: 4,
  lfo1Depth: 0,
  lfo1RateMode: "free",
  lfo1Division: "1/4",
  lfo2Wave: "triangle",
  lfo2Target: "off",
  lfo2Rate: 0.5,
  lfo2Depth: 0,
  lfo2RateMode: "free",
  lfo2Division: "1/4",
  fxDelayTime: 32,
  fxDelayFeedback: 22,
  fxDelayMix: 12,
  fxChorusRate: 26,
  fxChorusDepth: 18,
  fxChorusMix: 10,
  fxReverbSize: 36,
  fxReverbMix: 14,
  fxDistDrive: 8,
  fxDistMix: 6,
  masterVolume: 0.6,
};

export const TARGET_LABELS = {
  reserved: "Reserved",
  expression: "Expression",
  sustainPedal: "Sustain pedal",
  allSoundOff: "All sound off",
  allNotesOff: "All notes off",
  masterVolume: "Master volume",
  filterQ: "Filter resonance",
  filterCutoff: "Filter cutoff",
  attack: "Attack",
  decay: "Decay",
  release: "Release",
  osc1Level: "Osc 1 level",
  osc2Level: "Osc 2 level",
  osc1Detune: "Osc 1 detune",
  osc2Detune: "Osc 2 detune",
  osc1Octave: "Osc 1 octave",
  osc2Octave: "Osc 2 octave",
  lfo1Rate: "LFO 1 rate",
  lfo1Depth: "LFO 1 depth",
  lfo2Rate: "LFO 2 rate",
  lfo2Depth: "LFO 2 depth",
  lfo1RateMode: "LFO 1 rate mode",
  lfo2RateMode: "LFO 2 rate mode",
  lfo1Division: "LFO 1 division",
  lfo2Division: "LFO 2 division",
  fxDelayTime: "Delay time",
  fxDelayFeedback: "Delay feedback",
  fxDelayMix: "Delay mix",
  fxChorusRate: "Chorus rate",
  fxChorusDepth: "Chorus depth",
  fxChorusMix: "Chorus mix",
  fxReverbSize: "Reverb size",
  fxReverbMix: "Reverb mix",
  fxDistDrive: "Distortion drive",
  fxDistMix: "Distortion mix",
};
